version: '3'
services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '8000:80'
        environment:
            - NODE_ENV=production
            - REACT_APP_NAME=somProd
        # env_file:
        #   - ./.env
        command: node index.js
