---
name: Check
on:
  - push
jobs:
  check:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    container: node:latest
    steps:
      - run: node --version
      - run: npm --version